# Generated by Django 3.0.6 on 2020-08-02 05:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=7000)),
                ('email', models.EmailField(default='', max_length=254)),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(default='', max_length=50)),
                ('about_the_author', models.TextField(max_length=700)),
                ('author_image', models.ImageField(blank=True, default='user.png', upload_to='author_images')),
                ('blog_image', models.ImageField(blank=True, default='default.jpg', upload_to='blog_images')),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
