# Generated by Django 3.0.6 on 2020-08-08 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='event',
        ),
    ]
