# Generated by Django 3.0.6 on 2020-08-02 05:55

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.CharField(max_length=200)),
                ('startups_funded', models.CharField(default='', max_length=500)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='Add country code before the contact no.', max_length=128, null=True, region=None)),
                ('email', models.EmailField(default='', max_length=254)),
                ('photo', models.ImageField(default='', upload_to='vc/')),
            ],
        ),
    ]
