# Generated by Django 3.0.6 on 2020-08-08 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='startup_logo',
            field=models.ImageField(default='startup/download.png', upload_to='startup/'),
        ),
    ]
